export const projectShowcaseData = [
  {
    id: 1,
    title: "E-commerce Platform",
    category: "Dashboard · Shopify",
    image: "https://picsum.photos/id/1015/600/380",
    accent: "emerald",
  },
  {
    id: 2,
    title: "SaaS Analytics Suite",
    category: "Web App · Dashboard",
    image: "https://picsum.photos/id/201/600/380",
    accent: "blue",
  },
  {
    id: 3,
    title: "Health & Wellness App",
    category: "Mobile · UX Design",
    image: "https://picsum.photos/id/251/600/380",
    accent: "purple",
  },
  {
    id: 4,
    title: "Real Estate Portal",
    category: "Web Design · Development",
    image: "https://picsum.photos/id/133/600/380",
    accent: "amber",
  },
  {
    id: 5,
    title: "NFT Marketplace",
    category: "Web3 · UI/UX",
    image: "https://picsum.photos/id/180/600/380",
    accent: "pink",
  },
  {
    id: 6,
    title: "FinTech Dashboard",
    category: "Dashboard · Development",
    image: "https://picsum.photos/id/237/600/380",
    accent: "cyan",
  },
  {
    id: 7,
    title: "Corporate Branding Site",
    category: "Web Design · Branding",
    image: "https://picsum.photos/id/201/600/380",
    accent: "violet",
  },
  {
    id: 8,
    title: "EdTech Platform",
    category: "Full-Stack · SaaS",
    image: "https://picsum.photos/id/251/600/380",
    accent: "teal",
  },
  {
    id: 9,
    title: "Logistics Tracker",
    category: "Web App · Development",
    image: "https://picsum.photos/id/180/600/380",
    accent: "orange",
  },
];